import type { Chapter, Song, Character, Photo } from '@/types';

const createPhoto = (
  chapterId: number,
  src: string,
  caption: string,
  category: Photo['category'] = 'date'
): Photo => ({
  id: `${chapterId}-1`,
  src,
  caption,
  category,
});

const chapterSeed: Array<Omit<Chapter, 'month'>> = [
  {
    id: 1,
    title: 'Pertemuan Pertama',
    date: 'Juni 2024',
    description: 'Hari ketika dua jiwa bertemu untuk pertama kalinya.',
    story:
      'Aku masih mengingat waktu itu sewaktu kita pertama kali bertemu di CGV. Tatapan mata yang bertemu, senyum yang terukir, dan percakapan yang mengalir begitu canggung. Namun, momen ini menjadi awal dari perjalanan indah kita.',
    achievement: 'First Encounter Unlocked!',
    image: '/images/chapters/chapter-01.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(1, '/images/chapters/chapter-01.png', 'Pertemuan pertama kita')],
  },
  {
    id: 3,
    title: 'Pergi ke Event Bersama',
    date: 'Agustus 2024',
    description: 'Menghadiri event bersama untuk pertama kalinya.',
    story:
      'Di hari ini aku sangat excited karena bisa melihat kamu secara langsung cosplay menjadi Ada Wong. Meskipun selama event kita tidak melakukan kegiatan yang mencolok dan hanya mengobrol, aku tetap merasakan bahagia karena bisa melihat kamu seperti itu. Kita menutup hari ini dengan berpamitan di parkiran, kamu memberikan aku sebuah hadiah yang sampai hari ini masih aku gunakan, dan di sini kita melakukan pelukan pertama kita yang sedikit canggung itu.',
    achievement: 'Event Buddy Unlocked!',
    image: '/images/chapters/chapter-03.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(3, '/images/chapters/chapter-03.png', 'Event pertama kita bersama')],
  },
  {
    id: 4,
    title: 'Melukis di Taman',
    date: 'Agustus 2024',
    description: 'Hari cerah ketika kita melukis bersama di taman.',
    story:
      'Kita mengawali hari dengan CFD di Pare. Setelah itu, kita pergi ke taman untuk melukis gambar tangan kita di sebuah kanvas menggunakan warna pink dan biru. Sebenarnya, di hari ini aku ingin mengungkapkan perasaanku dan mengajak kamu membangun hubungan yang lebih serius, tetapi karena aku cukup malu, aku mengurungkan niat tersebut.',
    achievement: 'Artistic Duo Unlocked!',
    image: '/images/chapters/chapter-04.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(4, '/images/chapters/chapter-04.png', 'Hari kita melukis di taman', 'travel')],
  },
  {
    id: 5,
    title: 'Hari di Mana Kita Resmi Mengawali Hubungan',
    date: 'September 2024',
    description: 'Hari penuh cinta dan kebingungan.',
    story:
      'Aku sangat ingat saat aku mengungkapkan perasaanku di malam hari. Kamu merespons dengan sangat bingung dan takut karena kamu juga masih ragu untuk mengungkapkan perasaanmu. Namun, di pagi hari setelahnya kamu memberanikan diri untuk menerima cintaku, dan di situ aku merasakan kebahagiaan yang luar biasa. Aku merasa seperti mendapatkan hadiah terindah yang pernah aku dapatkan, dan aku sangat bersyukur sekali bisa memilikimu.',
    achievement: 'Love Unlocked!',
    image: '/images/chapters/chapter-05.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(5, '/images/chapters/chapter-05.png', 'Hari kita resmi bersama', 'travel')],
  },
  {
    id: 6,
    title: 'Kencan Pertama',
    date: 'September 2024',
    description: 'Kencan pertama yang penuh kegugupan dan kebahagiaan.',
    story:
      'Kencan pertama resmi kita adalah sewaktu kita berdua ketemu di Dinos. Diawali dengan janjian dulu ke Dinos, lalu aku menunggu kamu di depan cafe sampai kamu datang. Setelah kita berdua masuk, kita menikmati gelato yang begitu dingin, manis, dan enak. Di hari tersebut, kita memulai sebuah cerita kita yang sudah sejauh ini.',
    achievement: 'First Date Master!',
    image: '/images/chapters/chapter-02.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(2, '/images/chapters/chapter-02.png', 'Kencan pertama di Dinos')],
  },
  {
    id: 7,
    title: 'First Kiss',
    date: 'November 2024',
    description: 'Ciuman pertama yang penuh rasa gugup dan bahagia.',
    story:
      'Ini adalah salah satu momen paling membahagiakan di hidup aku. Aku masih ingat waktu itu kita melakukan sebuah keintiman, yaitu ciuman pertama kita di sebuah bioskop Golden saat menonton film RED ONE pada 16 November 2024. Di situ aku merasa deg-degan serta sangat bahagia karena ini adalah momen pertama kali di hidup aku melakukan ciuman.',
    achievement: 'First Kiss Unlocked!',
    image: '/images/chapters/chapter-06.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(6, '/images/chapters/chapter-06.png', 'Momen first kiss kita', 'travel')],
  },
  {
    id: 8,
    title: 'Tahun Baru yang Sepi',
    date: 'Desember 2024',
    description: 'Kita tidak bisa bertemu di malam tahun baru.',
    story:
      'Di penutup akhir tahun, sayang sekali kita tidak bisa bertemu di malam tahun baru karena ada halangan yang tidak bisa kita lalui :(',
    achievement: 'Tahun Baru yang Sepi :(',
    image: '/images/chapters/chapter-07.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(7, '/images/chapters/chapter-07.png', 'Penutup tahun yang terasa sepi', 'travel')],
  },
  {
    id: 9,
    title: 'Awal Tahun yang Kurang Semangat',
    date: 'Januari 2025',
    description: 'Kita memulai tahun dengan perasaan yang belum sepenuhnya pulih.',
    story:
      'Kita memulai tahun baru ini dengan semangat yang sedikit kurang karena kita mengalami banyak hal yang tidak baik di tahun sebelumnya.',
    achievement: 'Awal Tahun yang Berat, Tapi Kita Bisa Lewati!',
    image: '/images/chapters/chapter-08.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(8, '/images/chapters/chapter-08.png', 'Awal tahun yang terasa berat', 'travel')],
  },
  {
    id: 10,
    title: 'Kita Memasuki Fase Kamu Berfokus pada UTBK',
    date: 'Februari – April 2025',
    description: 'Masa ketika kita lebih sedikit bertemu karena fokus pada tujuanmu.',
    story:
      'Kita lebih sedikit bertemu di bulan-bulan ini karena kamu sedang fokus pada tujuan yang ingin kamu capai, yaitu UTBK. Di bulan tersebut juga ada bulan Ramadan, di mana kita sempat bertemu beberapa kali ketika berbuka di Laptul.',
    achievement: 'Berbuka Puasa di Laptul Unlocked!',
    image: '/images/chapters/chapter-09.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(9, '/images/chapters/chapter-09.png', 'Momen berbuka bersama di Laptul', 'travel')],
  },
  {
    id: 11,
    title: 'Kamu Ulang Tahun',
    date: 'Mei 2025',
    description: 'Hari spesial ketika aku bisa merayakan ulang tahunmu.',
    story:
      'Di hari ini kita memulai hari dengan sangat semangat karena ini adalah hari di mana kamu ulang tahun. Kita merayakan ulang tahun kamu di sebuah event tempat kamu cosplay. Aku sangat senang bisa merayakan ulang tahun kamu secara langsung, dan maaf ya kalau hadiah yang aku berikan tidak seberapa ^-^',
    achievement: 'Birthday Celebration Unlocked!',
    image: '/images/chapters/chapter-10.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(10, '/images/chapters/chapter-10.png', 'Perayaan ulang tahun kamu', 'travel')],
  },
  {
    id: 12,
    title: 'Bulan Hilang Harapan',
    date: 'Mei 2025',
    description: 'Bulan yang berat, tetapi kamu berhasil melewatinya dengan kuat.',
    story:
      'Setelah kita merayakan kebahagiaan ulang tahun kamu, di bulan yang sama kamu mengalami kesedihan yang tidak bisa aku bayangkan, yaitu kamu tidak lolos ikut SNBT. Di hari tersebut aku juga ikut sedih dan langsung kepikiran ke mana-mana karena aku takut kamu sangat down. Aku tahu bagaimana rasanya ditolak di universitas, tetapi aku ingat kamu bisa menghadapinya dengan sangat kuat. Tetap semangat sayang, kamu adalah orang yang kuat, dan aku percaya kamu bisa menghadapi semua ini dengan sangat baik. Aku selalu ada untuk kamu.',
    achievement: 'Stay Strong, My Love!',
    image: '/images/chapters/chapter-11.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(11, '/images/chapters/chapter-11.png', 'Masa sulit yang kamu lewati dengan kuat', 'travel')],
  },
  {
    id: 13,
    title: 'Bulan di Mana Kamu Pertama Kali ke Rumahku',
    date: 'Juni – Juli 2025',
    description: 'Kamu bermain ke rumahku untuk pertama kalinya.',
    story:
      'Di bulan ini kamu pertama kali ke rumah aku dengan perasaan yang gugup dan sangat tidak enakan. Namun, seiring berjalannya waktu, aku terus meyakinkan kamu agar tidak usah grogi dan anggap saja seperti di rumah sendiri. Di titik tertentu kamu mulai terbiasa, walaupun rasa tidak enakan itu belum sepenuhnya hilang.',
    achievement: 'First Visit to My Home Unlocked!',
    image: '/images/chapters/chapter-12.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(12, '/images/chapters/chapter-12.png', 'Pertama kali kamu datang ke rumahku', 'travel')],
  },
  {
    id: 14,
    title: 'Aku Ulang Tahun',
    date: 'Agustus 2025',
    description: 'Kamu merayakan ulang tahunku dengan penuh usaha dan cinta.',
    story:
      'Terima kasih sudah effort untuk merayakan ulang tahun aku di rumah aku. Aku sangat menghargai effort kamu untuk perjalanan jauhnya dan juga usaha kamu untuk memberikan aku hadiah yang menurut aku lebih berharga dari apa pun di dunia ini. Lukisan itu sangat teramat berharga sampai uang pun tidak bisa menggantinya. Kamu juga memberikan sebuah ucapan dan boneka buatan kamu sendiri. Fun fact, ini adalah pertama kali aku mendapatkan hadiah saat ulang tahun di usia aku yang sudah 20 tahun lebih. Aku sangat senang sekali bisa merayakan ulang tahunku dengan kamu. Terima kasih banyak sayang.',
    achievement: 'Makasiii Sayanggg!',
    image: '/images/chapters/chapter-13.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(13, '/images/chapters/chapter-13.png', 'Ulang tahunku yang spesial', 'travel')],
  },
  {
    id: 15,
    title: 'Bulan di Mana Kamu Masuk BEC',
    date: 'September 2025',
    description: 'Awal langkahmu memasuki BEC.',
    story:
      'Di bulan ini kamu pertama kali memasuki BEC dengan semangat dan penuh harapan (di waktu itu tapi) ^-^',
    achievement: 'Welcome to BEC, My Love!',
    image: '/images/chapters/chapter-14.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(14, '/images/chapters/chapter-14.png', 'Awal perjalananmu di BEC', 'travel')],
  },
  {
    id: 16,
    title: 'Bulan di Mana Kita Sering Bertemu di Rumahku',
    date: 'Akhir 2025',
    description: 'Di fase ini kita mulai sering bertemu di rumahku.',
    story:
      'Di akhir tahun kemarin kamu sering sekali berkunjung ke rumah aku karena aku tidak ada uang untuk pergi ke Pare. Aku sangat, sangat, sangat menghargai hal itu, walaupun ada hati kecil aku yang takut karena merasa aku belum mampu memberi banyak hal saat kita ingin bermain. Aku hanya bisa memberikan kamu makanan dan minuman saat kamu bermain ke rumahku, itupun terkadang kita melalui konflik yang kurang enak. Tapi makasih banget sudah effort. Aku berjanji akan sukses dan bisa membalas kamu dengan lebih baik lagi. Love u sayang.',
    achievement: 'Homebody Couple Unlocked!',
    image: '/images/chapters/chapter-15.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(15, '/images/chapters/chapter-15.png', 'Momen-momen sederhana di rumahku', 'travel')],
  },
  {
    id: 17,
    title: 'Kita Merayakan Tahun Baru',
    date: 'Desember 2025',
    description: 'Merayakan tahun baru bersama untuk pertama kalinya.',
    story:
      'Kita merayakan tahun baru bersama untuk pertama kalinya. Aku ingat sebelum berangkat aku membuat makanan dulu untuk kamu, karena kita tidak bisa ke mana-mana selain di tempat yang sederhana. Waktu itu aku berangkat sore dan sampai sekitar jam 5. Kita menghabiskan waktu dengan saling bercerita dan tukar makanan. Meskipun kita tidak sampai jam 12, aku sangat menikmati waktu bersama kamu saat itu.',
    achievement: 'New Year Celebration Unlocked!',
    image: '/images/chapters/chapter-16.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(16, '/images/chapters/chapter-16.png', 'Tahun baru pertama kita bersama', 'travel')],
  },
  {
    id: 18,
    title: 'Sampai Saat Ini',
    date: 'Januari 2026 – Sekarang',
    description: 'Perjalanan kita yang luar biasa selama lebih dari satu tahun.',
    story:
      'Aku sangat bersyukur bisa menjalani hubungan sejauh ini. Meskipun banyak rintangan yang sudah kita lalui, aku sadar banyak di antaranya datang dari kekuranganku sendiri: saat aku tidak punya uang, tidak bisa mengerti kamu, tidak bisa menahan amarah, dan tidak bisa menggunakan kata-kata yang sopan. Maaf banget ya aku masih seperti itu. Aku sadar aku salah. Untuk ke depannya, doakan saja dan dukung aku supaya aku bisa berubah. Terima kasih untuk perjalanan kita selama ini. Ini adalah hubungan terpanjang, komitmen terpanjang, dan perjalanan terbesar dalam hidup aku. Sekali lagi, terima kasih dan maaf yang sebesar-besarnya. Aku usahakan ke depannya aku bisa berubah menjadi lebih baik lagi.',
    achievement: 'Our Journey Continues Unlocked!',
    image: '/images/chapters/chapter-17.png',
    unlocked: true,
    completed: true,
    photos: [createPhoto(17, '/images/chapters/chapter-17.png', 'Perjalanan kita sampai hari ini', 'travel')],
  },
];
export const chapters: Chapter[] = chapterSeed.map((chapter, index) => ({
  ...chapter,
  month: index + 1,
}));

export const songs: Song[] = [
  { id: 1, title: 'Last Son', artist: 'David Fleming', duration: '2:45', src: '/audio/bgm/Superman.mp3' },
  { id: 2, title: "Five Nights at Freddy's 2", artist: 'The Living Tombstone', duration: '3:00', src: '/audio/bgm/Fnaf.mp3' },
  { id: 3, title: 'Love', artist: 'wave to earth', duration: '5:05', src: '/audio/bgm/Love.mp3' },
];

export const characters: Character[] = [
  {
    name: 'Aku',
    level: 99,
    hp: 'Infinite',
    mp: '100%',
    class: 'Soulmate',
    sprite: '/images/sprites/char-boy.png',
  },
  {
    name: 'Kamu',
    level: 99,
    hp: 'Infinite',
    mp: '100%',
    class: 'Partner',
    sprite: '/images/sprites/char-girl.png',
  },
];

export const photos: Photo[] = [
  { id: '1', src: '/images/ijat_hasil/foto1.jpg', caption: '', category: 'date' },
  { id: '2', src: '/images/ijat_hasil/foto2.jpg', caption: '', category: 'date' },
  { id: '3', src: '/images/ijat_hasil/foto3.jpg', caption: '', category: 'date' },
  { id: '4', src: '/images/ijat_hasil/foto4.jpg', caption: '', category: 'date' },
  { id: '5', src: '/images/ijat_hasil/foto5.jpg', caption: '', category: 'date' },
  { id: '6', src: '/images/ijat_hasil/foto6.jpg', caption: '', category: 'date' },
  { id: '7', src: '/images/ijat_hasil/foto7.jpg', caption: '', category: 'date' },
  { id: '8', src: '/images/ijat_hasil/foto8.jpg', caption: '', category: 'date' },
  { id: '9', src: '/images/ijat_hasil/foto9.jpg', caption: '', category: 'date' },
  { id: '10', src: '/images/ijat_hasil/foto10.jpg', caption: '', category: 'date' },
  { id: '11', src: '/images/ijat_hasil/foto11.jpg', caption: '', category: 'date' },
  { id: '12', src: '/images/ijat_hasil/foto12.jpg', caption: '', category: 'date' },
  { id: '13', src: '/images/ijat_hasil/foto13.jpg', caption: '', category: 'date' },
  { id: '14', src: '/images/ijat_hasil/foto14.jpg', caption: '', category: 'date' },
  { id: '15', src: '/images/ijat_hasil/foto15.jpg', caption: '', category: 'date' },
  { id: '16', src: '/images/ijat_hasil/foto16.jpg', caption: '', category: 'date' },
  { id: '17', src: '/images/ijat_hasil/foto17.jpg', caption: '', category: 'date' },
  { id: '18', src: '/images/ijat_hasil/foto18.jpg', caption: '', category: 'date' },
  { id: '19', src: '/images/ijat_hasil/foto19.jpg', caption: '', category: 'date' },
  { id: '20', src: '/images/ijat_hasil/foto20.jpg', caption: '', category: 'date' },
  { id: '21', src: '/images/ijat_hasil/foto21.jpg', caption: '', category: 'date' },
  { id: '22', src: '/images/ijat_hasil/foto22.jpg', caption: '', category: 'date' },
  { id: '23', src: '/images/ijat_hasil/foto23.jpg', caption: '', category: 'date' },
  { id: '24', src: '/images/ijat_hasil/foto24.jpg', caption: '', category: 'date' },
  { id: '25', src: '/images/ijat_hasil/foto25.jpg', caption: '', category: 'date' },
  { id: '26', src: '/images/ijat_hasil/foto26.jpg', caption: '', category: 'date' },
  { id: '27', src: '/images/ijat_hasil/foto27.jpg', caption: '', category: 'date' },
  { id: '28', src: '/images/ijat_hasil/foto28.jpg', caption: '', category: 'date' },
  { id: '29', src: '/images/ijat_hasil/foto29.jpg', caption: '', category: 'date' },
  { id: '30', src: '/images/ijat_hasil/foto30.jpg', caption: '', category: 'date' },
  { id: '31', src: '/images/ijat_hasil/foto31.jpg', caption: '', category: 'date' },
  { id: '32', src: '/images/ijat_hasil/foto32.jpg', caption: '', category: 'date' },
  { id: '33', src: '/images/ijat_hasil/foto33.jpg', caption: '', category: 'date' },
  { id: '34', src: '/images/ijat_hasil/foto34.jpg', caption: '', category: 'date' },
  { id: '35', src: '/images/ijat_hasil/foto35.jpg', caption: '', category: 'date' },
  { id: '36', src: '/images/ijat_hasil/foto36.jpg', caption: '', category: 'date' },
  { id: '37', src: '/images/ijat_hasil/foto37.jpg', caption: '', category: 'date' },
  { id: '38', src: '/images/ijat_hasil/foto38.jpg', caption: '', category: 'date' },
  { id: '39', src: '/images/ijat_hasil/foto39.jpg', caption: '', category: 'date' },
  { id: '40', src: '/images/ijat_hasil/foto40.jpg', caption: '', category: 'date' },
  { id: '41', src: '/images/ijat_hasil/foto41.jpg', caption: '', category: 'date' },
  { id: '42', src: '/images/ijat_hasil/foto42.jpg', caption: '', category: 'date' },
  { id: '43', src: '/images/ijat_hasil/foto43.jpg', caption: '', category: 'date' },
  { id: '44', src: '/images/ijat_hasil/foto44.jpg', caption: '', category: 'date' },
  { id: '45', src: '/images/ijat_hasil/foto45.jpg', caption: '', category: 'date' },
  { id: '46', src: '/images/ijat_hasil/foto46.jpg', caption: '', category: 'date' },
  { id: '47', src: '/images/ijat_hasil/foto47.jpg', caption: '', category: 'date' },
  { id: '48', src: '/images/ijat_hasil/foto48.jpg', caption: '', category: 'date' },
  { id: '49', src: '/images/ijat_hasil/foto49.jpg', caption: '', category: 'date' },
  { id: '50', src: '/images/ijat_hasil/foto50.jpg', caption: '', category: 'date' },
  { id: '51', src: '/images/ijat_hasil/foto51.jpg', caption: '', category: 'date' },
  { id: '52', src: '/images/ijat_hasil/foto52.jpg', caption: '', category: 'date' },
  { id: '53', src: '/images/ijat_hasil/foto53.jpg', caption: '', category: 'date' },
  { id: '54', src: '/images/ijat_hasil/foto54.jpg', caption: '', category: 'date' },
  { id: '55', src: '/images/ijat_hasil/foto55.jpg', caption: '', category: 'date' },
  { id: '56', src: '/images/ijat_hasil/foto56.jpg', caption: '', category: 'date' },
  { id: '57', src: '/images/ijat_hasil/foto57.jpg', caption: '', category: 'date' },
  { id: '58', src: '/images/ijat_hasil/foto58.jpg', caption: '', category: 'date' },
  { id: '59', src: '/images/ijat_hasil/foto59.jpg', caption: '', category: 'date' },
  { id: '60', src: '/images/ijat_hasil/foto60.jpg', caption: '', category: 'date' },
  { id: '61', src: '/images/ijat_hasil/foto61.jpg', caption: '', category: 'date' },
  { id: '62', src: '/images/ijat_hasil/foto62.jpg', caption: '', category: 'date' },
  { id: '63', src: '/images/ijat_hasil/foto63.jpg', caption: '', category: 'date' },
  { id: '64', src: '/images/ijat_hasil/foto64.jpg', caption: '', category: 'date' },
  { id: '65', src: '/images/ijat_hasil/foto65.jpg', caption: '', category: 'date' },
  { id: '66', src: '/images/ijat_hasil/foto66.jpg', caption: '', category: 'date' },
  { id: '67', src: '/images/ijat_hasil/foto67.jpg', caption: '', category: 'date' },
  { id: '68', src: '/images/ijat_hasil/foto68.jpg', caption: '', category: 'date' },
  { id: '69', src: '/images/ijat_hasil/foto69.jpg', caption: '', category: 'date' },
  { id: '70', src: '/images/ijat_hasil/foto70.jpg', caption: '', category: 'date' },
  { id: '71', src: '/images/ijat_hasil/foto71.jpg', caption: '', category: 'date' },
  { id: '72', src: '/images/ijat_hasil/foto72.jpg', caption: '', category: 'date' },
  { id: '73', src: '/images/ijat_hasil/foto73.jpg', caption: '', category: 'date' },
  { id: '74', src: '/images/ijat_hasil/foto74.jpg', caption: '', category: 'date' },
  { id: '75', src: '/images/ijat_hasil/foto75.jpg', caption: '', category: 'date' },
  { id: '76', src: '/images/ijat_hasil/foto76.jpg', caption: '', category: 'date' },
  { id: '77', src: '/images/ijat_hasil/foto77.jpg', caption: '', category: 'date' },
  { id: '78', src: '/images/ijat_hasil/foto78.jpg', caption: '', category: 'date' },
  { id: '79', src: '/images/ijat_hasil/foto79.jpg', caption: '', category: 'date' },
  { id: '80', src: '/images/ijat_hasil/foto80.jpg', caption: '', category: 'date' },
  { id: '81', src: '/images/ijat_hasil/foto81.jpg', caption: '', category: 'date' },
  { id: '82', src: '/images/ijat_hasil/foto82.jpg', caption: '', category: 'date' },
  { id: '83', src: '/images/ijat_hasil/foto83.jpg', caption: '', category: 'date' },
  { id: '84', src: '/images/ijat_hasil/foto84.jpg', caption: '', category: 'date' },
  { id: '85', src: '/images/ijat_hasil/foto85.jpg', caption: '', category: 'date' },
  { id: '86', src: '/images/ijat_hasil/foto86.jpg', caption: '', category: 'date' },
  { id: '87', src: '/images/ijat_hasil/foto87.jpg', caption: '', category: 'date' },
  { id: '88', src: '/images/ijat_hasil/foto88.jpg', caption: '', category: 'date' },
  { id: '89', src: '/images/ijat_hasil/foto89.jpg', caption: '', category: 'date' },
  { id: '90', src: '/images/ijat_hasil/foto90.jpg', caption: '', category: 'date' },
  { id: '91', src: '/images/ijat_hasil/foto91.jpg', caption: '', category: 'date' },
  { id: '92', src: '/images/ijat_hasil/foto92.jpg', caption: '', category: 'date' },
  { id: '93', src: '/images/ijat_hasil/foto93.jpg', caption: '', category: 'date' },
  { id: '94', src: '/images/ijat_hasil/foto94.jpg', caption: '', category: 'date' },
  { id: '95', src: '/images/ijat_hasil/foto95.jpg', caption: '', category: 'date' },
  { id: '96', src: '/images/ijat_hasil/foto96.jpg', caption: '', category: 'date' },
  { id: '97', src: '/images/ijat_hasil/foto97.jpg', caption: '', category: 'date' },
  { id: '98', src: '/images/ijat_hasil/foto98.jpg', caption: '', category: 'date' },
  { id: '99', src: '/images/ijat_hasil/foto99.jpg', caption: '', category: 'date' },
  { id: '100', src: '/images/ijat_hasil/foto100.jpg', caption: '', category: 'date' },
  { id: '101', src: '/images/ijat_hasil/foto101.jpg', caption: '', category: 'date' },
  { id: '102', src: '/images/ijat_hasil/foto102.jpg', caption: '', category: 'date' },
  { id: '103', src: '/images/ijat_hasil/foto103.jpg', caption: '', category: 'date' },
  { id: '104', src: '/images/ijat_hasil/foto104.jpg', caption: '', category: 'date' },
  { id: '105', src: '/images/ijat_hasil/foto105.jpg', caption: '', category: 'date' },
  { id: '106', src: '/images/ijat_hasil/foto106.jpg', caption: '', category: 'date' },
  { id: '107', src: '/images/ijat_hasil/foto107.jpg', caption: '', category: 'date' },
  { id: '108', src: '/images/ijat_hasil/foto108.jpg', caption: '', category: 'date' },
  { id: '109', src: '/images/ijat_hasil/foto109.jpg', caption: '', category: 'date' },
  { id: '110', src: '/images/ijat_hasil/foto110.jpg', caption: '', category: 'date' },
  { id: '111', src: '/images/ijat_hasil/foto111.jpg', caption: '', category: 'date' },
  { id: '112', src: '/images/ijat_hasil/foto112.jpg', caption: '', category: 'date' },
  { id: '113', src: '/images/ijat_hasil/foto113.jpg', caption: '', category: 'date' },
  { id: '114', src: '/images/ijat_hasil/foto114.jpg', caption: '', category: 'date' },
  { id: '115', src: '/images/ijat_hasil/foto115.jpg', caption: '', category: 'date' },
  { id: '116', src: '/images/ijat_hasil/foto116.jpg', caption: '', category: 'date' },
  { id: '117', src: '/images/ijat_hasil/foto117.jpg', caption: '', category: 'date' },
  { id: '118', src: '/images/ijat_hasil/foto118.jpg', caption: '', category: 'date' },
  { id: '119', src: '/images/ijat_hasil/foto119.jpg', caption: '', category: 'date' },
  { id: '120', src: '/images/ijat_hasil/foto120.jpg', caption: '', category: 'date' },
  { id: '121', src: '/images/ijat_hasil/foto121.jpg', caption: '', category: 'date' },
  { id: '122', src: '/images/ijat_hasil/foto122.jpg', caption: '', category: 'date' },
  { id: '123', src: '/images/ijat_hasil/foto123.jpg', caption: '', category: 'date' },
  { id: '124', src: '/images/ijat_hasil/foto124.jpg', caption: '', category: 'date' },
  { id: '125', src: '/images/ijat_hasil/foto125.jpg', caption: '', category: 'date' },
  { id: '126', src: '/images/ijat_hasil/foto126.jpg', caption: '', category: 'date' },
  { id: '127', src: '/images/ijat_hasil/foto127.jpg', caption: '', category: 'date' },
  { id: '128', src: '/images/ijat_hasil/foto128.jpg', caption: '', category: 'date' },
  { id: '129', src: '/images/ijat_hasil/foto129.jpg', caption: '', category: 'date' },
  { id: '130', src: '/images/ijat_hasil/foto130.jpg', caption: '', category: 'date' },
  { id: '131', src: '/images/ijat_hasil/foto131.jpg', caption: '', category: 'date' },
  { id: '132', src: '/images/ijat_hasil/foto132.jpg', caption: '', category: 'date' },
  { id: '133', src: '/images/ijat_hasil/foto133.jpg', caption: '', category: 'date' },
  { id: '134', src: '/images/ijat_hasil/foto134.jpg', caption: '', category: 'date' },
  { id: '135', src: '/images/ijat_hasil/foto135.jpg', caption: '', category: 'date' },
  { id: '136', src: '/images/ijat_hasil/foto136.jpg', caption: '', category: 'date' },
  { id: '137', src: '/images/ijat_hasil/foto137.jpg', caption: '', category: 'date' },
  { id: '138', src: '/images/ijat_hasil/foto138.jpg', caption: '', category: 'date' },
  { id: '139', src: '/images/ijat_hasil/foto139.jpg', caption: '', category: 'date' },
  { id: '140', src: '/images/ijat_hasil/foto140.jpg', caption: '', category: 'date' },
  { id: '141', src: '/images/ijat_hasil/foto141.jpg', caption: '', category: 'date' },
  { id: '142', src: '/images/ijat_hasil/foto142.jpg', caption: '', category: 'date' },
  { id: '143', src: '/images/ijat_hasil/foto143.jpg', caption: '', category: 'date' },
  { id: '144', src: '/images/ijat_hasil/foto144.jpg', caption: '', category: 'date' },
  { id: '145', src: '/images/ijat_hasil/foto145.jpg', caption: '', category: 'date' },
  { id: '146', src: '/images/ijat_hasil/foto146.jpg', caption: '', category: 'date' },
  { id: '147', src: '/images/ijat_hasil/foto147.jpg', caption: '', category: 'date' },
  { id: '148', src: '/images/ijat_hasil/foto148.jpg', caption: '', category: 'date' },
  { id: '149', src: '/images/ijat_hasil/foto149.jpg', caption: '', category: 'date' },
  { id: '150', src: '/images/ijat_hasil/foto150.jpg', caption: '', category: 'date' },
  { id: '151', src: '/images/ijat_hasil/foto151.jpg', caption: '', category: 'date' },
  { id: '152', src: '/images/ijat_hasil/foto152.jpg', caption: '', category: 'date' },
  { id: '153', src: '/images/ijat_hasil/foto153.jpg', caption: '', category: 'date' },
  { id: '154', src: '/images/ijat_hasil/foto154.jpg', caption: '', category: 'date' },
  { id: '155', src: '/images/ijat_hasil/foto155.jpg', caption: '', category: 'date' },
  { id: '156', src: '/images/ijat_hasil/foto156.jpg', caption: '', category: 'date' },
  { id: '157', src: '/images/ijat_hasil/foto157.jpg', caption: '', category: 'date' },
  { id: '158', src: '/images/ijat_hasil/foto158.jpg', caption: '', category: 'date' },
  { id: '159', src: '/images/ijat_hasil/foto159.jpg', caption: '', category: 'date' },
  { id: '160', src: '/images/ijat_hasil/foto160.jpg', caption: '', category: 'date' },
  { id: '161', src: '/images/ijat_hasil/foto161.jpg', caption: '', category: 'date' },
  { id: '162', src: '/images/ijat_hasil/foto162.jpg', caption: '', category: 'date' },
  { id: '163', src: '/images/ijat_hasil/foto163.jpg', caption: '', category: 'date' },
  { id: '164', src: '/images/ijat_hasil/foto164.jpg', caption: '', category: 'date' },
  { id: '165', src: '/images/ijat_hasil/foto165.jpg', caption: '', category: 'date' },
  { id: '166', src: '/images/ijat_hasil/foto166.jpg', caption: '', category: 'date' },
  { id: '167', src: '/images/ijat_hasil/foto167.jpg', caption: '', category: 'date' },
  { id: '168', src: '/images/ijat_hasil/foto168.jpg', caption: '', category: 'date' },
  { id: '169', src: '/images/ijat_hasil/foto169.jpg', caption: '', category: 'date' },
  { id: '170', src: '/images/ijat_hasil/foto170.jpg', caption: '', category: 'date' },
  { id: '171', src: '/images/ijat_hasil/foto171.jpg', caption: '', category: 'date' },
  { id: '172', src: '/images/ijat_hasil/foto172.jpg', caption: '', category: 'date' },
  { id: '173', src: '/images/ijat_hasil/foto173.jpg', caption: '', category: 'date' },
  { id: '174', src: '/images/ijat_hasil/foto174.jpg', caption: '', category: 'date' },
  { id: '175', src: '/images/ijat_hasil/foto175.jpg', caption: '', category: 'date' },
  { id: '176', src: '/images/ijat_hasil/foto176.jpg', caption: '', category: 'date' },
  { id: '177', src: '/images/ijat_hasil/foto177.jpg', caption: '', category: 'date' },
  { id: '178', src: '/images/ijat_hasil/foto178.jpg', caption: '', category: 'date' },
  { id: '179', src: '/images/ijat_hasil/foto179.jpg', caption: '', category: 'date' },
  { id: '180', src: '/images/ijat_hasil/foto180.jpg', caption: '', category: 'date' },
  { id: '181', src: '/images/ijat_hasil/foto181.jpg', caption: '', category: 'date' },
  { id: '182', src: '/images/ijat_hasil/foto182.jpg', caption: '', category: 'date' },
  { id: '183', src: '/images/ijat_hasil/foto183.jpg', caption: '', category: 'date' },
  { id: '184', src: '/images/ijat_hasil/foto184.jpg', caption: '', category: 'date' },
  { id: '185', src: '/images/ijat_hasil/foto185.jpg', caption: '', category: 'date' },
  { id: '186', src: '/images/ijat_hasil/foto186.jpg', caption: '', category: 'date' },
  { id: '187', src: '/images/ijat_hasil/foto187.jpg', caption: '', category: 'date' },
  { id: '188', src: '/images/ijat_hasil/foto188.jpg', caption: '', category: 'date' },
  { id: '189', src: '/images/ijat_hasil/foto189.jpg', caption: '', category: 'date' },
  { id: '190', src: '/images/ijat_hasil/foto190.jpg', caption: '', category: 'date' },
  { id: '191', src: '/images/ijat_hasil/foto191.jpg', caption: '', category: 'date' },
  { id: '192', src: '/images/ijat_hasil/foto192.jpg', caption: '', category: 'date' },
  { id: '193', src: '/images/ijat_hasil/foto193.jpg', caption: '', category: 'date' },
  { id: '194', src: '/images/ijat_hasil/foto194.jpg', caption: '', category: 'date' },
  { id: '195', src: '/images/ijat_hasil/foto195.jpg', caption: '', category: 'date' },
  { id: '196', src: '/images/ijat_hasil/foto196.jpg', caption: '', category: 'date' },
  { id: '197', src: '/images/ijat_hasil/foto197.jpg', caption: '', category: 'date' },
  { id: '198', src: '/images/ijat_hasil/foto198.jpg', caption: '', category: 'date' },
  { id: '199', src: '/images/ijat_hasil/foto199.jpg', caption: '', category: 'date' },
  { id: '200', src: '/images/ijat_hasil/foto200.jpg', caption: '', category: 'date' },
  { id: '201', src: '/images/ijat_hasil/foto201.jpg', caption: '', category: 'date' },
  { id: '202', src: '/images/ijat_hasil/foto202.jpg', caption: '', category: 'date' },
  { id: '203', src: '/images/ijat_hasil/foto203.jpg', caption: '', category: 'date' },
  { id: '204', src: '/images/ijat_hasil/foto204.jpg', caption: '', category: 'date' },
  { id: '205', src: '/images/ijat_hasil/foto205.jpg', caption: '', category: 'date' },
  { id: '206', src: '/images/ijat_hasil/foto206.jpg', caption: '', category: 'date' },
  { id: '207', src: '/images/ijat_hasil/foto207.jpg', caption: '', category: 'date' },
  { id: '208', src: '/images/ijat_hasil/foto208.jpg', caption: '', category: 'date' },
  { id: '209', src: '/images/ijat_hasil/foto209.jpg', caption: '', category: 'date' },
  { id: '210', src: '/images/ijat_hasil/foto210.jpg', caption: '', category: 'date' },
  { id: '211', src: '/images/ijat_hasil/foto211.jpg', caption: '', category: 'date' },
  { id: '212', src: '/images/ijat_hasil/foto212.jpg', caption: '', category: 'date' },
  { id: '213', src: '/images/ijat_hasil/foto213.jpg', caption: '', category: 'date' },
  { id: '214', src: '/images/ijat_hasil/foto214.jpg', caption: '', category: 'date' },
  { id: '215', src: '/images/ijat_hasil/foto215.jpg', caption: '', category: 'date' },
  { id: '216', src: '/images/ijat_hasil/foto216.jpg', caption: '', category: 'date' },
  { id: '217', src: '/images/ijat_hasil/foto217.jpg', caption: '', category: 'date' },
  { id: '218', src: '/images/ijat_hasil/foto218.jpg', caption: '', category: 'date' },
  { id: '219', src: '/images/ijat_hasil/foto219.jpg', caption: '', category: 'date' },
  { id: '220', src: '/images/ijat_hasil/foto220.jpg', caption: '', category: 'date' },
  { id: '221', src: '/images/ijat_hasil/foto221.jpg', caption: '', category: 'date' },
  { id: '222', src: '/images/ijat_hasil/foto222.jpg', caption: '', category: 'date' },
  { id: '223', src: '/images/ijat_hasil/foto223.jpg', caption: '', category: 'date' },
  { id: '224', src: '/images/ijat_hasil/foto224.jpg', caption: '', category: 'date' },
  { id: '225', src: '/images/ijat_hasil/foto225.jpg', caption: '', category: 'date' },
  { id: '226', src: '/images/ijat_hasil/foto226.jpg', caption: '', category: 'date' },
  { id: '227', src: '/images/ijat_hasil/foto227.jpg', caption: '', category: 'date' },
  { id: '228', src: '/images/ijat_hasil/foto228.jpg', caption: '', category: 'date' },
];

export const getChapterById = (id: number): Chapter | undefined => {
  return chapters.find((chapter) => chapter.id === id);
};

export const getUnlockedChapters = (): Chapter[] => {
  return chapters.filter((chapter) => chapter.unlocked);
};

export const getCompletedChapters = (): Chapter[] => {
  return chapters.filter((chapter) => chapter.completed);
};
